Added check for existing *.war files in detect script

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,5 +1,56 @@
 #!/usr/bin/env bash
 # bin/detect <build-dir>
 
+BUILD_DIR="$1"
+
+error() {
+    local c="2,999 s/^/ !     /"
+    # send all of our output to stderr
+    exec 1>&2
+    
+    echo -e "\033[1;31m" # bold; red
+    echo -n " !     ERROR: "
+    # this will be fed from stdin
+    case "$(uname)" in
+        Darwin) sed -u "$c";; # mac/bsd sed: -l buffers on line boundaries
+        *)      sed -u "$c";; # unix/gnu sed: -u unbuffered (arbitrary) chunks of data
+    esac
+    echo -e "\033[0m" # reset style
+    exit 1
+}
+
+warFiles=("${BUILD_DIR}"/target/*.war)
+if [ "${warFiles[*]}" == "${BUILD_DIR}/target/*.war" ]; then
+    error <<EOF
+No WAR files found in 'target' directory for deployment
+
+This buildpack requires *.war files to be existing right under the 'target'
+directory, but none could be found there. There can be 2 reasons for this:
+
+  1) You did not add the official Heroku Java Buildpack to your application
+     which builds the codebase and produces an output WAR file.
+  2) Your Maven build configuration does not specify WAR packaging.
+
+The first issue can be resolved by adding the Heroku Java Buildpack to the
+application with these commands:
+
+  heroku buildpacks:clear
+  heroku buildpacks:add heroku/java
+  heroku buildpacks:add https://github.com/mortenterhart/heroku-buildpack-wildfly
+
+The order of the builpacks is important here: First the application is
+built using 'heroku/java' and then this buildpack installs a WildFly
+instance on top of it.
+
+To get Maven create a WAR file for your application you have to set the
+packaging type to 'war' and add the 'maven-war-plugin' as a plugin to your
+configuration.
+
+For more information refer to the official usage guide:
+https://maven.apache.org/plugins/maven-war-plugin/usage.html
+EOF
+    exit 1
+fi
+
 echo "WildFly"
 exit 0
